import { useEffect, useMemo, useState } from 'react'
import { Search, Filter, Plus, Pencil, Trash2, X } from 'lucide-react'
import { inventoryService } from '../services/database'
import './InventorySection.css'

const blankItem = { name: '', category: '', sku: '', price: '', quantity: '', unit: 'kg', image_url: '' }
const statusFor = (item) => Number(item.quantity) === 0 ? 'Out of stock' : Number(item.quantity) <= 10 ? 'Low stock' : 'In stock'
function StockStatusBadge({ status }) { return <span className={`inventory-status ${status === 'In stock' ? 'inventory-status--in-stock' : status === 'Low stock' ? 'inventory-status--low-stock' : 'inventory-status--out-of-stock'}`}>{status}</span> }

export default function InventorySection() {
  const [inventory, setInventory] = useState([]); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false)
  const [error, setError] = useState(''); const [notice, setNotice] = useState(''); const [searchQuery, setSearchQuery] = useState(''); const [categoryFilter, setCategoryFilter] = useState('all'); const [showFilter, setShowFilter] = useState(false)
  const [editing, setEditing] = useState(null); const [form, setForm] = useState(blankItem)
  const load = async () => { setLoading(true); try { setInventory(await inventoryService.list()); setError('') } catch (err) { setError(err.message) } finally { setLoading(false) } }
  useEffect(() => { load() }, [])
  const categories = useMemo(() => [...new Set(inventory.map(i => i.category))], [inventory])
  const items = useMemo(() => inventory.filter(item => (categoryFilter === 'all' || item.category === categoryFilter) && (!searchQuery || item.name.toLowerCase().includes(searchQuery.toLowerCase()) || item.sku.toLowerCase().includes(searchQuery.toLowerCase()))), [inventory, categoryFilter, searchQuery])
  const flash = message => { setNotice(message); setTimeout(() => setNotice(''), 3500) }
  const openForm = (item = null) => { setEditing(item?.id || 'new'); setForm(item ? { ...item, price: String(item.price), quantity: String(item.quantity) } : blankItem) }
  const save = async e => { e.preventDefault(); if (!form.name.trim() || !form.category.trim() || !form.sku.trim() || form.price === '' || form.quantity === '' || Number(form.price) < 0 || Number(form.quantity) < 0) return setError('Complete all required fields with valid price and quantity.'); setSaving(true); try { const values = { ...form, price: Number(form.price), quantity: Number(form.quantity) }; const result = editing === 'new' ? await inventoryService.create(values) : await inventoryService.update(editing, values); setInventory(current => editing === 'new' ? [...current, result] : current.map(item => item.id === result.id ? result : item)); setEditing(null); setError(''); flash(editing === 'new' ? 'Product created successfully.' : 'Inventory updated successfully.') } catch (err) { setError(err.message) } finally { setSaving(false) } }
  const remove = async id => { if (!window.confirm('Delete this inventory item?')) return; try { await inventoryService.remove(id); setInventory(items => items.filter(item => item.id !== id)); flash('Inventory item deleted successfully.') } catch (err) { setError(err.message) } }
  return <div className="inventory-section animate-fade-in-up">
    {(error || notice) && <div className={`mb-4 rounded-xl p-3 text-sm ${error ? 'bg-red-50 text-red-700' : 'bg-green-50 text-green-700'}`}>{error || notice}</div>}
    {editing && <form onSubmit={save} className="mb-5 rounded-2xl border border-gray-200 bg-white p-5 shadow-sm"><div className="mb-4 flex items-center justify-between"><h3 className="font-bold">{editing === 'new' ? 'Add Product' : 'Edit Product'}</h3><button type="button" onClick={() => setEditing(null)}><X /></button></div><div className="grid gap-3 md:grid-cols-3">{[['name','Product name'],['category','Category'],['sku','SKU'],['price','Price'],['quantity','Quantity'],['unit','Unit'],['image_url','Image URL']].map(([field,label]) => <label key={field} className="text-xs font-semibold text-gray-600">{label}<input required={field !== 'image_url'} value={form[field]} type={['price','quantity'].includes(field) ? 'number' : 'text'} min={['price','quantity'].includes(field) ? 0 : undefined} onChange={e => setForm({ ...form, [field]: e.target.value })} className="mt-1 w-full rounded-lg border p-2" /></label>)}</div><button disabled={saving} className="mt-4 rounded-xl bg-[#e32929] px-4 py-2 text-xs font-bold text-white">{saving ? 'Saving…' : 'Save Product'}</button></form>}
    <div className="inventory-toolbar"><div className="inventory-search-wrap"><Search className="inventory-search-icon"/><input value={searchQuery} onChange={e => setSearchQuery(e.target.value)} placeholder="Search by product name" className="inventory-search-input"/></div><div className="inventory-toolbar-actions"><div className="inventory-filter-group"><button onClick={() => setShowFilter(!showFilter)} className="inventory-filter-btn"><Filter className="w-4 h-4"/>Filter</button>{showFilter && <div className="inventory-filter-dropdown"><p className="inventory-filter-label">Category</p><select value={categoryFilter} onChange={e => setCategoryFilter(e.target.value)} className="inventory-filter-select"><option value="all">All Categories</option>{categories.map(cat => <option key={cat}>{cat}</option>)}</select></div>}</div><button onClick={() => openForm()} className="inventory-add-btn"><Plus className="w-4 h-4"/>Add Product</button></div></div>
    {loading ? <div className="inventory-empty">Loading inventory…</div> : <div className="inventory-table-card hidden md:block"><table className="inventory-table"><thead><tr><th>Product</th><th>Category</th><th>Stock Quantity</th><th>Stock Status</th><th>Action</th></tr></thead><tbody>{items.map(item => <tr key={item.id}><td><div className="inventory-product-cell">{item.image_url ? <img src={item.image_url} alt="" className="inventory-product-img"/> : <div className="inventory-product-img bg-gray-100"/>}<div><span className="inventory-product-name">{item.name}</span><span className="inventory-product-meta">{item.sku} · ₹{Number(item.price).toLocaleString('en-IN')}</span></div></div></td><td className="inventory-cell-text">{item.category}</td><td className="inventory-cell-text">{item.quantity} {item.unit}</td><td><StockStatusBadge status={statusFor(item)}/></td><td><div className="inventory-action-group"><button onClick={() => openForm(item)} className="inventory-update-btn">Update Stock</button><button onClick={() => openForm(item)} className="inventory-icon-btn inventory-icon-btn--edit"><Pencil className="w-3.5 h-3.5"/></button><button onClick={() => remove(item.id)} className="inventory-icon-btn inventory-icon-btn--delete"><Trash2 className="w-3.5 h-3.5"/></button></div></td></tr>)}</tbody></table>{!items.length && <div className="inventory-empty">No inventory items found.</div>}</div>}
  </div>
}
