import { useEffect, useMemo, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { Search, Eye } from 'lucide-react'
import { offerService } from '../services/database'

const offerStatus = offer => offer.disabled || new Date(offer.end_date || offer.endDate) < new Date() ? 'Expired' : new Date(offer.start_date || offer.startDate) > new Date() ? 'Scheduled' : 'Active'
export default function OffersSection() {
  const navigate = useNavigate(); const [offers, setOffers] = useState([]); const [loading, setLoading] = useState(true); const [search, setSearch] = useState(''); const [tab, setTab] = useState('all')
  useEffect(() => { let active = true; offerService.list().then(data => active && setOffers(data)).finally(() => active && setLoading(false)); return () => { active = false } }, [])
  const visible = useMemo(() => offers.filter(offer => (tab === 'all' || offerStatus(offer).toLowerCase() === tab) && (!search || offer.title?.toLowerCase().includes(search.toLowerCase()) || offer.code?.toLowerCase().includes(search.toLowerCase()))), [offers, tab, search])
  return <div className="space-y-6 animate-fade-in-up"><div><h2 className="text-xl font-bold text-gray-900">Offers</h2><p className="text-xs text-gray-400">View active promotions.</p></div><div className="flex flex-wrap gap-3"><div className="flex items-center rounded-xl border bg-white px-3"><Search className="mr-2 h-4 w-4 text-gray-400"/><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Search offers" className="py-2 text-sm outline-none"/></div>{['all','active','scheduled','expired'].map(value => <button key={value} onClick={() => setTab(value)} className={`rounded-xl px-3 py-2 text-xs font-bold ${tab === value ? 'bg-red-50 text-[#e32929]' : 'bg-white text-gray-500'}`}>{value}</button>)}</div><div className="overflow-hidden rounded-2xl border border-gray-150 bg-white shadow-sm">{loading ? <div className="p-8 text-center text-gray-400">Loading offers…</div> : <table className="w-full text-left text-xs"><thead className="bg-gray-50 text-gray-400"><tr><th className="p-4">Offer</th><th className="p-4">Discount</th><th className="p-4">Validity</th><th className="p-4">Status</th><th className="p-4">Details</th></tr></thead><tbody>{visible.map(offer => <tr key={offer.id} className="border-t"><td className="p-4 font-bold">{offer.title}<div className="mt-1 text-gray-400">{offer.code}</div></td><td className="p-4">{offer.type === 'Percentage' ? `${offer.discount_value ?? offer.discountValue}%` : offer.type === 'Flat' ? `₹${offer.discount_value ?? offer.discountValue}` : 'Free delivery'}</td><td className="p-4">{offer.start_date || offer.startDate} – {offer.end_date || offer.endDate}</td><td className="p-4">{offerStatus(offer)}</td><td className="p-4"><button onClick={() => navigate(`/offers/${offer.id}`)}><Eye className="h-4 w-4"/></button></td></tr>)}{!visible.length && <tr><td colSpan="5" className="p-8 text-center text-gray-400">No data available.</td></tr>}</tbody></table>}</div></div>
}
